---
baseurl: "/"
permalink: "/:title/"
title: Snipcart
snipcart_js: https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js
snipcart_css: https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css
snipcart_api_key: YTc4NjE5OTYtM2M3MC00MDc4LWE2MTktZWIxNDBhMDNlYTIyNjM3MTA0ODkyNTYxOTg1NTY5
logos:
  light:
    optimized: images/logo-white.svg
    fallback: images/logo-white.svg
  dark:
    optimized: images/logo.svg
    fallback: images/logo.svg
palette: default
palettes:
  default:
    sass:
      default: "#FFFFFF"
      light: "#F0F0F0"
      medium: "#6B797A"
      dark: "#384647"
      active: "#88b3dd"
      active_light: "#b6e3fd"
      active_medium: "#5c7091"
      active_dark: "#546375"
      dark_grey: "#273132"
      light_grey: "#6B797A"
      bg_image_primary_optimized: "/images/cover-home.webp"
      bg_image_primary_fallback: "/images/cover-home.png"
      bg_image_secondary_optimized: "/images/leaf-light-grey.svg"
      bg_image_secondary_fallback: "/images/leaf-light-grey.svg"
      bg_image_product_optimized: "/images/leaf.svg"
      bg_image_product_fallback: "/images/leaf.svg"
      bg_image_cart_optimized: "/images/cart-bg.webp"
      bg_image_cart_fallback: "/images/header.jpg"
sass:
  style: nested
  precision: 10
plugins:
- jekyll-menus
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
