---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- name: image
  type: file
  config:
    maxSize: 250
  label: SEO-Image
  description: an image to use in SEO
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - smartphones
    - airpods
    - apple-watch
    - imac
    - ipad
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
- name: gallery
  type: image_gallery
  config: {}
  label: gallery
  description: gallery images for product
- name: colortags
  type: tag_list
  default: []
  label: Colortags
pages:
- products/apple-watch-sport-serie-4-gps-celular-40mm.md
- products/desktop-apple-imac-pro-xeon-mq2y2ll-a.md
- products/imac-apple-mmqa2ll-a.md
- products/imac-apple-mndy2ll-a.md
- products/apple-imac-mne92ll.md
- products/ipad-apple-new-128gb-4g.md
- products/pad-apple-new-32gb-wi-fi.md
- products/ipad-new-128gb-wi-fi.md
- products/apple-imac-mk472-27-retina-5k-intel-core-i5-quad-3-2ghz-8gb-1tb.md
- products/ipad-new-32gb-4g.md
- products/apple-imac-mk482-4core-i5-qc-3-3ghz.md
- products/plant3.md
- products/plant4.md
- products/iphone-xs-max-512.md
- products/iphone-xs-64gb.md
- products/iphone-xr-64gb.md
- products/iphone-xr-128gb.md
- products/iphone-7-128gb-plus-4g-desbloqueado.md
- products/apple-airpods-fone-de-ouvido-sem-fio-wireless.md
- products/iphone-xs-max-256gb.md
- products/iphone-xr-256gb.md
- products/iphone-x-256gb.md
- products/iphone-7-256gb-plus-4g-desbloqueado.md
- products/iphone-7-256gb-4g-desbloqueado.md
- products/plant9.md
- products/plant6.md
- products/apple-watch-sport-serie-3-42mm-gps.md
- products/apple-watch-series-4-44-mm-a2008-mtvu2bz-a-gps-celular.md
- products/plant5.md
- products/iphone-8-256gb.md
- products/apple-watch-serie-3-38m-gps.md
- products/plant2.md
- products/apple-watch-sport-serie-4-40mm-gps.md
- products/plant1.md
- products/plant7.md
- products/iphone-xs-256gb.md
- products/iphone-7-128gb-desbloqueado.md
- products/plant8.md
- products/iphone-xs-max-64gb.md
- products/iphone-6s-64gb.md
- products/iphone-8-256-plus.md
- products/iphone-8-64gb-plus.md
- products/iphone-8-64gb.md
