---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- name: price
  type: text
  config:
    required: false
  label: Price
- name: image
  type: file
  config:
    maxSize: 250
  label: SEO-Image
  description: an image to use in SEO
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - smartphones
    - airpods
    - apple-watch
    - imac
    - ipad
    - macbook-air
    - macbook-pro-tela-retina
    - macbook-pro-touch-bar
    - cabos
    - ipad-pro
    - gopro
- name: sub-category
  type: select
  default: []
  config:
    required: false
    options:
    - Adaptadores
    - Carregador
    - Fonte
    - Lightning
    - USB-C
    source:
      type: simple
      section: sub-categories
      file: 
      path: 
  label: Sub-Category
  description: choose a sub-category
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
- name: gallery
  type: image_gallery
  config: {}
  label: gallery
  description: gallery images for product
- name: colortags
  type: tag_list
  default: []
  label: Colortags
pages:
- products/apple-imac-mk472-27-retina-5k-intel-core-i5-quad-3-2ghz-8gb-1tb.md
- products/apple-airpods-fone-de-ouvido-sem-fio-wireless.md
- products/imac-apple-mndy2ll-a.md
- products/gopro-hero-5-session.md
- products/apple-carregador-fonte-5w-md810ea-padrao-americano.md
- products/gopro-hero-5-black.md
- products/carregador-apple-megasefe-2-85w.md
- products/carregador-apple-megasefe-1-85w.md
- products/apple-ipad-pro-10-5-64gb-wi-fi.md
- products/apple-ipad-pro-10-5-512gb-wi-fi-4g.md
- products/apple-ipad-pro-10-5-512gb-wi-fi.md
- products/apple-ipad-pro-10-5-256gb-wi-fi.md
- products/plant5.md
- products/plant4.md
- products/plant2.md
- products/plant1.md
- products/ipad-pro-12-9-256gb-wi-fi.md
- products/filmadora-gopro-hero7-black.md
- products/filmadora-gopro-hero-6-preto.md
- products/cabo-usb-c-apple-2-mts-mll82am.md
- products/cabo-usb-c.md
- products/cabo-lightning-usb-com-2-metros-para-iphone-ipod-ipad-branco.md
- products/cabo-apple-lightning-para-iphone-ipad-e-ipod.md
- products/apple-ipad-pro-10-5-256gb-wi-fi-4g.md
- products/adaptador-usb-c-para-digital-av-multiporta-apple.md
- products/ipad-pro-12-9-64gb-wi-fi.md
- products/ipad-pro-12-9-512gb-wi-fi.md
- products/ipad-apple-new-128gb-4g.md
- products/desktop-apple-imac-pro-xeon-mq2y2ll-a.md
- products/apple-macbook-air-mqd42ll-a.md
- products/apple-macbook-pro-mpxu2ll-a1708.md
- products/apple-macbook-pro-touch-bar-mptw2ll-a-a1707-15-4-de-3-1ghz-16gb-ram-1tb-ssd.md
- products/ipad-new-32gb-4g.md
- products/apple-imac-mk482-4core-i5-qc-3-3ghz.md
- products/pad-apple-new-32gb-wi-fi.md
- products/apple-macbook-pro-mr932ll-a-touch-bar-intel-core-i7-2-2ghz-memória-16gb-ssd-256gb-15-4.md
- products/apple-macbook-pro-touch-bar-mr9r2ll-a-a1989-13-3-de-2-3ghz-8gb-ram-512gb-ssd.md
- products/apple-imac-mne92ll.md
- products/apple-macbook-pro-touch-bar-mr9q2ll-a-a1989-13-3-de-2-3ghz-8gb-ram-256gb-ssd-cinza-espacial.md
- products/apple-macbook-air-mrec2ll-a.md
- products/apple-macbook-pro-mpxq2ll-a-a1708.md
- products/ipad-pro-12-9-256gb-4g.md
- products/apple-watch-sport-serie-4-gps-celular-40mm.md
- products/ipad-new-128gb-wi-fi.md
- products/imac-apple-mmqa2ll-a.md
- products/apple-macbook-pro-touch-bar-mr942ll-a-a1990-15-4-intel-core-i7-16gb-ram-512gb-ssd-cinza-espacial.md
- products/ipad-pro-12-9-64gb-4g.md
- products/apple-macbook-pro-mpxr2ll-a-a1708.md
- products/apple-macbook-air-mref2ll-a.md
- products/iphone-x-256gb.md
- products/iphone-8-64gb.md
- products/iphone-8-64gb-plus.md
- products/iphone-8-256gb.md
- products/iphone-8-256-plus.md
- products/iphone-6s-64gb.md
- products/iphone-xs-256gb.md
- products/iphone-xs-max-256gb.md
- products/iphone-xs-max-512.md
- products/iphone-xs-max-64gb.md
- products/plant8.md
- products/plant9.md
- products/iphone-7-128gb-desbloqueado.md
- products/plant3.md
- products/plant7.md
- products/apple-watch-sport-serie-4-40mm-gps.md
- products/apple-watch-sport-serie-3-42mm-gps.md
- products/apple-watch-series-4-44-mm-a2008-mtvu2bz-a-gps-celular.md
- products/apple-watch-serie-3-38m-gps.md
- products/iphone-7-256gb-4g-desbloqueado.md
- products/iphone-7-256gb-plus-4g-desbloqueado.md
- products/iphone-xr-256gb.md
- products/iphone-7-128gb-plus-4g-desbloqueado.md
- products/iphone-xr-128gb.md
- products/iphone-xr-64gb.md
- products/iphone-xs-64gb.md
- products/plant6.md
